Added argument to showUnlock method
doordeck/doordeck-sdk-react-native pull request #23
Opened 2022-03-03 16:54 UTC by endritbajrami

The argument is a boolean value that indicates whether scan type should be NFC or QR.

2022-03-08 08:36 UTC, RafaRuiz commented
Hello @endritbajrami , thanks for your contribution.
This is a breaking change for the javascript bridge function `showUnlock`, which didn't have any parameters earlier and will have them now.
The parameter `isNfc` is a boolean and before we assumed it was true, so can you please add the default parameter true to `isNfc` ?

2022-11-08 22:40 UTC, endritbajrami commented
Sorry for the late response 😅

2022-11-09 14:11 UTC, RafaRuiz requested changes

2022-11-09 14:11 UTC, RafaRuiz commented on index.js
> +const showUnlock = (isNfc) => RNDoordeckSdk.showUnlock(isNfc);
Breaking changes, please add this `isNfc` parameter as default (true)

2022-11-09 20:07 UTC, endritbajrami commented
I also added this fix https://github.com/facebook/react-native/issues/35210 recommended by react-native team

2022-11-19 13:51 UTC, RafaRuiz approved these changes

2022-11-19 13:51 UTC, merged